/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as FilesRouteImport } from './routes/files'
import { Route as ExtractorsRouteImport } from './routes/extractors'
import { Route as DatawarehouseRouteImport } from './routes/datawarehouse'
import { Route as DatalakeRouteImport } from './routes/datalake'
import { Route as IndexRouteImport } from './routes/index'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractorsRoute = ExtractorsRouteImport.update({
  id: '/extractors',
  path: '/extractors',
  getParentRoute: () => rootRouteImport,
} as any)
const DatawarehouseRoute = DatawarehouseRouteImport.update({
  id: '/datawarehouse',
  path: '/datawarehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const DatalakeRoute = DatalakeRouteImport.update({
  id: '/datalake',
  path: '/datalake',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datalake': typeof DatalakeRoute
  '/datawarehouse': typeof DatawarehouseRoute
  '/extractors': typeof ExtractorsRoute
  '/files': typeof FilesRoute
  '/runs': typeof RunsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datalake': typeof DatalakeRoute
  '/datawarehouse': typeof DatawarehouseRoute
  '/extractors': typeof ExtractorsRoute
  '/files': typeof FilesRoute
  '/runs': typeof RunsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datalake': typeof DatalakeRoute
  '/datawarehouse': typeof DatawarehouseRoute
  '/extractors': typeof ExtractorsRoute
  '/files': typeof FilesRoute
  '/runs': typeof RunsRoute
  '/sources': typeof SourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datalake'
    | '/datawarehouse'
    | '/extractors'
    | '/files'
    | '/runs'
    | '/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datalake'
    | '/datawarehouse'
    | '/extractors'
    | '/files'
    | '/runs'
    | '/sources'
  id:
    | '__root__'
    | '/'
    | '/datalake'
    | '/datawarehouse'
    | '/extractors'
    | '/files'
    | '/runs'
    | '/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatalakeRoute: typeof DatalakeRoute
  DatawarehouseRoute: typeof DatawarehouseRoute
  ExtractorsRoute: typeof ExtractorsRoute
  FilesRoute: typeof FilesRoute
  RunsRoute: typeof RunsRoute
  SourcesRoute: typeof SourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extractors': {
      id: '/extractors'
      path: '/extractors'
      fullPath: '/extractors'
      preLoaderRoute: typeof ExtractorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datawarehouse': {
      id: '/datawarehouse'
      path: '/datawarehouse'
      fullPath: '/datawarehouse'
      preLoaderRoute: typeof DatawarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datalake': {
      id: '/datalake'
      path: '/datalake'
      fullPath: '/datalake'
      preLoaderRoute: typeof DatalakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatalakeRoute: DatalakeRoute,
  DatawarehouseRoute: DatawarehouseRoute,
  ExtractorsRoute: ExtractorsRoute,
  FilesRoute: FilesRoute,
  RunsRoute: RunsRoute,
  SourcesRoute: SourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
